### PR TITLE
 $http .success method removed in angular v1.6.0, use .then method instead.

### PR DESCRIPTION
**Pull request by woaij007**
Deprecation Notice
The $http legacy promise methods .success and .error have been deprecated and will be removed in v1.6.0. Use the standard .then method
instead.

### CODE REVIEW

**Comment by scooterguthrie** [comment]
Thanks, this works great!

**Comment by suvjunmd** [comment]
@m00s, please merge this

**Comment by maroun-baydoun** [comment]
@m00s Any plans to release a new version on npm containing this fix?

**Comment by CatBakun** [comment]
Hello, I'm also needing this fix to be merged. @m00s  Do you know when is this going to be published?

Thanks

**Pull request merged**
